2019-04-04 15:01:04 [scrapy.core.scraper] ERROR: Error processing {'detail': '["小泉今日子 二阶堂富美 高良健吾 板尾创路 山田裕贵 黑川芽以", "前田司郎", "日本", "剧情片 大陆剧", "日语", '
           '"2016"]',
 'film_name': '伤心往事',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/190331/757e2b9b663f7f10.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '伤心往事' for key 'PRIMARY'")
2019-04-04 15:01:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index73286.html> (referer: https://www.1716dy.com/frim/index14-2.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:01:20 [scrapy.core.scraper] ERROR: Error processing {'detail': '["李·佩斯 贝纳尼丝·玛尔洛", "Joe", "美国", "科幻片 海外剧", "英语对白", "2017"]',
 'film_name': '铁甲战神',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/ab790806c5cf0996.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '铁甲战神' for key 'PRIMARY'")
2019-04-04 15:01:28 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56351.html> (referer: https://www.1716dy.com/frim/index49-5.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:01:30 [scrapy.core.scraper] ERROR: Error processing {'detail': '["吉拉宇·唐思苏克 金伯莉·安妮 楠迪·宗拉维蒙", "Pa Jaew", "泰国", "海外剧", "泰语", "2017"]',
 'film_name': '天鹅套索2017',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/2d6402fa1275a1ba.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '天鹅套索2017' for key 'PRIMARY'")
2019-04-04 15:01:31 [scrapy.core.scraper] ERROR: Error processing {'detail': '["连奕名 邵兵 林威", "连奕名", "大陆", "大陆剧 动作片", "国语对白", "2016"]',
 'film_name': '回马枪 电视剧',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/2f9e27bd28a3ecc7.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '回马枪 电视剧' for key 'PRIMARY'")
2019-04-04 15:01:32 [scrapy.core.scraper] ERROR: Error processing {'detail': '["赖拉·邦雅淑安德鲁·格莱格森披查亚·尼迪裴善官", "内详", "泰国", "海外剧 动作片", "泰语对白", "2016"]',
 'film_name': '我的老公是特工',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/96b10b1d5c70e121.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '我的老公是特工' for key 'PRIMARY'")
2019-04-04 15:01:48 [scrapy.core.scraper] ERROR: Error processing {'detail': '["黎耀祥 毛舜筠 陈国邦", "邵丽琼", "其他", "港台剧 喜剧片", "国语/粤", "2016"]',
 'film_name': '爱回家之八时入席',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181116/d7a0950ab798f5c6.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '爱回家之八时入席' for key 'PRIMARY'")
2019-04-04 15:01:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index57507.html> (referer: https://www.1716dy.com/frim/index14-9.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:01:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index52045.html> (referer: https://www.1716dy.com/frim/index14-9.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:01:50 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index46706.html> (referer: https://www.1716dy.com/frim/index14-9.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:01:51 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index38140.html> (referer: https://www.1716dy.com/frim/index13-12.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:02:04 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index51803.html> (referer: https://www.1716dy.com/frim/index14-13.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:27 [scrapy.core.scraper] ERROR: Error processing {'detail': '["赵达 张陆 骆达华", "姜凯阳", "大陆", "大陆剧", "国语", "2017"]',
 'film_name': '卧底第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/201812/4b909f261806d87a.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '卧底第一季' for key 'PRIMARY'")
2019-04-04 15:02:38 [scrapy.core.scraper] ERROR: Error processing {'detail': '["许魏洲 黄景瑜 陈稳 林枫松", "丁伟", "大陆", "大陆剧 喜剧片", "国语对白", "2016"]',
 'film_name': '上瘾',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/180929/e42cea41942fc290.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '上瘾' for key 'PRIMARY'")
2019-04-04 15:02:43 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56239.html> (referer: https://www.1716dy.com/frim/index15-2.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:46 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index72994.html> (referer: https://www.1716dy.com/frim/index15-3.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55740.html> (referer: https://www.1716dy.com/frim/index15-4.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56101.html> (referer: https://www.1716dy.com/frim/index15-4.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55739.html> (referer: https://www.1716dy.com/frim/index15-4.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55948.html> (referer: https://www.1716dy.com/frim/index42-11.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67628.html> (referer: https://www.1716dy.com/frim/index42-13.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68045.html> (referer: https://www.1716dy.com/frim/index42-13.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:02:58 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68102.html> (referer: https://www.1716dy.com/frim/index42-13.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67885.html> (referer: https://www.1716dy.com/frim/index42-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68059.html> (referer: https://www.1716dy.com/frim/index42-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:00 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68653.html> (referer: https://www.1716dy.com/frim/index42-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:01 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67701.html> (referer: https://www.1716dy.com/frim/index42-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:01 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67629.html> (referer: https://www.1716dy.com/frim/index42-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:02 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56087.html> (referer: https://www.1716dy.com/frim/index42-15.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:02 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55733.html> (referer: https://www.1716dy.com/frim/index42-15.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:03 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68172.html> (referer: https://www.1716dy.com/frim/index42-15.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:03 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67627.html> (referer: https://www.1716dy.com/frim/index42-15.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:05 [scrapy.core.scraper] ERROR: Error processing {'detail': '["王祖蓝 王源 王俊凯", "郑芬芬", "大陆", "大陆剧 科幻片", "国语对白", "2016"]',
 'film_name': '超少年密码',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181112/ea8a5134833b8c33.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '超少年密码' for key 'PRIMARY'")
2019-04-04 15:03:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69178.html> (referer: https://www.1716dy.com/frim/index42-16.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:08 [scrapy.core.scraper] ERROR: Error processing {'detail': '["Melissa O\'Neil 安东尼·莱姆克", "内详", "日本", "欧美剧", "英语", "2017"]',
 'film_name': '黑暗物质第三季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/180927/e4e15dfd1b89e6cf.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'Neil 安东尼·莱姆克", "内详", "日本", "欧美剧", "英语", "2017"]\',\' at line 1')
2019-04-04 15:03:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69381.html> (referer: https://www.1716dy.com/frim/index42-16.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69334.html> (referer: https://www.1716dy.com/frim/index42-16.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68832.html> (referer: https://www.1716dy.com/frim/index42-16.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68136.html> (referer: https://www.1716dy.com/frim/index42-16.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:11 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68858.html> (referer: https://www.1716dy.com/frim/index42-17.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:11 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69084.html> (referer: https://www.1716dy.com/frim/index42-17.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:11 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69602.html> (referer: https://www.1716dy.com/frim/index42-17.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:11 [scrapy.core.scraper] ERROR: Error processing {'detail': '["蒂莫西·赫顿 莫里·柴金", "蒂莫西·赫顿 John L\'Ecuyer", "美国", "欧美剧", "内详", '
           '"2001"]',
 'film_name': '大侦探尼罗·沃尔夫',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/bb73970d2b2aba41.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'Ecuyer", "美国", "欧美剧", "内详", "2001"]\',\'https://www.1716dy.comhttps:\' at line 1')
2019-04-04 15:03:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index67887.html> (referer: https://www.1716dy.com/frim/index42-17.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69530.html> (referer: https://www.1716dy.com/frim/index42-17.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:15 [scrapy.core.scraper] ERROR: Error processing {'detail': '["北野武 山田孝之 吉田羊 满岛光 桥爪功 胜村政信", "深川荣洋", "日本", "日韩剧 剧情片", "日语", '
           '"2017"]',
 'film_name': '破狱',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/180928/6870da8eee16b05b.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '破狱' for key 'PRIMARY'")
2019-04-04 15:03:17 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55731.html> (referer: https://www.1716dy.com/frim/index42-19.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:23 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68988.html> (referer: https://www.1716dy.com/frim/index42-20.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:25 [scrapy.core.scraper] ERROR: Error processing {'detail': '["薇诺娜·瑞德 大卫·哈伯 卡拉·布欧诺", "肖恩·利维", "美国", "欧美剧 恐怖片", "英语对白", "2015"]',
 'film_name': '怪奇物语第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181130/32d6eee922622ccf.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '怪奇物语第一季' for key 'PRIMARY'")
2019-04-04 15:03:26 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index60283.html> (referer: https://www.1716dy.com/frim/index42-21.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:26 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53619.html> (referer: https://www.1716dy.com/frim/index42-21.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:31 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index60643.html> (referer: https://www.1716dy.com/frim/index42-23.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:32 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55738.html> (referer: https://www.1716dy.com/frim/index42-23.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:34 [scrapy.core.scraper] ERROR: Error processing {'detail': '["亚瑟·达维尔 维克多·加博 凯蒂·洛茨 温特沃斯·米勒 多米尼克·珀塞尔", "德莫特·唐斯", "欧美", "欧美剧 '
           '科幻片", "英语对白", "2016"]',
 'film_name': '明日传奇第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/160415/7d5404675d6c4933.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '明日传奇第一季' for key 'PRIMARY'")
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index65715.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index63743.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index58163.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56027.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55890.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53591.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index50413.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:36 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index46716.html> (referer: https://www.1716dy.com/frim/index15-14.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index69493.html> (referer: https://www.1716dy.com/frim/index42-24.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55336.html> (referer: https://www.1716dy.com/frim/index42-24.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:40 [scrapy.core.scraper] ERROR: Error processing {'detail': '["胜地凉山﨑努泷本美织", "宇佐川隆史", "日本", "日韩剧 喜剧片", "日语对白", "2016"]',
 'film_name': '“滚蛋吧”少爷',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181119/8c9621ada4bccad7.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '“滚蛋吧”少爷' for key 'PRIMARY'")
2019-04-04 15:03:47 [scrapy.core.scraper] ERROR: Error processing {'detail': '["村上淳 上地雄輔 木村祐一", "品川ヒロシ", "日本", "日韩剧 动作片", "日语对白", "2016"]',
 'film_name': 'Z岛：关东黑道火拼篇',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/eac926dbbd4089ed.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'Z岛：关东黑道火拼篇' for key 'PRIMARY'")
2019-04-04 15:03:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index46703.html> (referer: https://www.1716dy.com/frim/index42-26.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53646.html> (referer: https://www.1716dy.com/frim/index42-26.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:03:51 [scrapy.core.scraper] ERROR: Error processing {'detail': '["松井珠理奈 戸次重幸 清原果耶", "渡瀬暁彦", "日本", "欧美剧 恐怖片", "日语对白", "2016"]',
 'film_name': '死币DEATHCASH',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/b06f5ce2348b17bd.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '死币DEATHCASH' for key 'PRIMARY'")
2019-04-04 15:03:52 [scrapy.core.scraper] ERROR: Error processing {'detail': '["格雷戈·莫里斯 彼得·格雷夫斯 芭芭拉·贝恩", "布鲁斯·盖勒", "美国", "欧美剧 动作片", "英语对白", '
           '"1966"]',
 'film_name': '谍中谍第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181119/141a65aac8cc16b8.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '谍中谍第一季' for key 'PRIMARY'")
2019-04-04 15:03:52 [scrapy.core.scraper] ERROR: Error processing {'detail': '["佐藤二朗 渡辺麻友 佐藤仁美", "福田雄一", "日本", "日韩剧 喜剧片", "日语对白", "2016"]',
 'film_name': '逗比铁三角',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/5dc27dc06693d3c0.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '逗比铁三角' for key 'PRIMARY'")
2019-04-04 15:04:02 [scrapy.core.scraper] ERROR: Error processing {'detail': '["内详", "详见视频", "泰国", "欧美剧 动作片", "泰语对白", "2016"]',
 'film_name': '我老公是特工',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/0f5217ede33a10c6.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '我老公是特工' for key 'PRIMARY'")
2019-04-04 15:04:05 [scrapy.core.scraper] ERROR: Error processing {'detail': '["森川葵 高桥一生 阳月华", "池田千寻", "日本", "日韩剧", "日语对白", "2016"]',
 'film_name': '公主小屋',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/08cfc105f7f26ce3.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '公主小屋' for key 'PRIMARY'")
2019-04-04 15:04:05 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index68634.html> (referer: https://www.1716dy.com/frim/index13-32.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:06 [scrapy.core.scraper] ERROR: Error processing {'detail': '["Merle Dandridge Kim Hawthorne Lynn Whitfield", "克莱门·维果", "美国", '
           '"欧美剧", "英语", "2016"]',
 'film_name': '绿叶第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181116/87799009a2e18ca7.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '绿叶第一季' for key 'PRIMARY'")
2019-04-04 15:04:07 [scrapy.core.scraper] ERROR: Error processing {'detail': '["罗伯特·沃恩 大卫·麦考姆 里奥.G.卡罗尔", "Barry Shear", "美国", "欧美剧", "英语", '
           '"2016"]',
 'film_name': '大叔局特工第三季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181116/12f35f949f5fff8a.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '大叔局特工第三季' for key 'PRIMARY'")
2019-04-04 15:04:07 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index35828.html> (referer: https://www.1716dy.com/frim/index13-32.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:12 [scrapy.core.scraper] ERROR: Error processing {'detail': '["伊利斯 莱韦斯克 卢卡斯·布莱恩特", "Sudz", "英国", "欧美剧", "英语对白", "2016"]',
 'film_name': '枪杀信使第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/618a6aadcef0c715.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '枪杀信使第一季' for key 'PRIMARY'")
2019-04-04 15:04:14 [scrapy.core.scraper] ERROR: Error processing {'detail': '["二阶堂富美 坂口健太郎 大野拓朗", "国本雅広", "日本", "日韩剧", "日语对白", "2016"]',
 'film_name': '热血老师',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181115/c285b872f9ab4403.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '热血老师' for key 'PRIMARY'")
2019-04-04 15:04:22 [scrapy.core.scraper] ERROR: Error processing {'detail': '["泽村一树 和久井映见 樱田日和 二宫庆多 伊藤和枝 六角精儿 宫川一朗太 中岛博子 や..", "深川荣洋", "日本", '
           '"日韩剧", "日语", "2016"]',
 'film_name': '希望之丘的人们',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/d3ba98d6c3679387.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '希望之丘的人们' for key 'PRIMARY'")
2019-04-04 15:04:25 [scrapy.core.scraper] ERROR: Error processing {'detail': '["藤原龙也 玉山铁二 二阶堂富美", "佐藤东弥", "日本", "日韩剧 剧情片", "日语发音", "2016"]',
 'film_name': '遗失身份',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/c57769ac683edbb4.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '遗失身份' for key 'PRIMARY'")
2019-04-04 15:04:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55334.html> (referer: https://www.1716dy.com/frim/index15-25.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55131.html> (referer: https://www.1716dy.com/frim/index15-26.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:47 [scrapy.core.scraper] ERROR: Error processing {'detail': '["安吉拉·贝塞特 阿尔菲·艾伦 Ciara Charteris", "斯蒂芬·波利亚科夫", "美国", "欧美剧", "英语", '
           '"2016"]',
 'film_name': '与敌为伴第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181126/0db7a0e30a91a9e5.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '与敌为伴第一季' for key 'PRIMARY'")
2019-04-04 15:04:47 [scrapy.core.scraper] ERROR: Error processing {'detail': '["金南佶 金雅中 刘旻奎", "洪忠灿", "韩国", "日韩剧", "韩语", "20167"]',
 'film_name': '名不虚传',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181130/69fac801c88530c2.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '名不虚传' for key 'PRIMARY'")
2019-04-04 15:04:49 [scrapy.core.scraper] ERROR: Error processing {'detail': '["周雨彤 侯明昊 贺军翔 秦汉", "江丰宏", "大陆", "大陆剧", "国语", "2017"]',
 'film_name': '寒武纪',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/a4e76c09fc209461.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '寒武纪' for key 'PRIMARY'")
2019-04-04 15:04:50 [scrapy.core.scraper] ERROR: Error processing {'detail': '["白客 孔连顺 郑合惠子", "内详", "其他", "大陆剧", "未知", "2017"]',
 'film_name': '鲜肉老师',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/832c7105f568601e.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '鲜肉老师' for key 'PRIMARY'")
2019-04-04 15:04:51 [scrapy.core.scraper] ERROR: Error processing {'detail': '["罗莎里奥·道森 凯瑟琳·海格尔 吉欧夫·斯图兹 伊莎贝拉·瑞思", "丹尼斯·蒂诺威", "美国", "日韩剧 剧情片", '
           '"英语对白", "2017"]',
 'film_name': '难以忘怀',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/66eccb575d6eda51.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '难以忘怀' for key 'PRIMARY'")
2019-04-04 15:04:51 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53412.html> (referer: https://www.1716dy.com/frim/index15-29.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:51 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53372.html> (referer: https://www.1716dy.com/frim/index15-29.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:04:52 [scrapy.core.scraper] ERROR: Error processing {'detail': '["澎恰恰 陈汉典 赖琳恩 阿喜 郭子干", "内详", "内地", "大陆剧", "国语", "2017"]',
 'film_name': '我的胡搅年代',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/4057a7688fca7e7e.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '我的胡搅年代' for key 'PRIMARY'")
2019-04-04 15:04:52 [scrapy.core.scraper] ERROR: Error processing {'detail': '["张陆 赵达 骆达华 曲高位 徐露 邢宇菲 陳菲", "姜凯阳", "大陆", "大陆剧", "普通话对", "2017"]',
 'film_name': '卧底第二季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/215a505173534bc2.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '卧底第二季' for key 'PRIMARY'")
2019-04-04 15:04:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index34921.html> (referer: https://www.1716dy.com/frim/index13-42.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:04:54 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index47299.html> (referer: https://www.1716dy.com/frim/index13-43.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:04:54 [scrapy.core.scraper] ERROR: Error processing {'detail': '["金宇彬 裴秀智 林周焕", "朴铉锡", "韩国", "日韩剧", "韩语", "2017"]',
 'film_name': '任意依恋',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/a6aaad7b730767e0.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '任意依恋' for key 'PRIMARY'")
2019-04-04 15:04:56 [scrapy.core.scraper] ERROR: Error processing {'detail': '["王阳 罗仲谦 罗嘉良", "洪金泼", "大陆", "大陆剧", "国语对白", "2016"]',
 'film_name': '无间道无间风云再起',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/fd1224853195c8ce.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '无间道无间风云再起' for key 'PRIMARY'")
2019-04-04 15:05:00 [scrapy.core.scraper] ERROR: Error processing {'detail': '["凯瑟琳·凯丽 法蒂·艾沙耶德 彼得·卡帕尔蒂", "Ed", "英国", "欧美剧 科幻片", "英语对白", "2016"]',
 'film_name': '神秘校园第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/cac989fd90b962fd.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '神秘校园第一季' for key 'PRIMARY'")
2019-04-04 15:05:00 [scrapy.core.scraper] ERROR: Error processing {'detail': '["Bea Arthur Betty White Rue McClanahan", "Lex Passaris", "美国", '
           '"欧美剧", "英语", "2016"]',
 'film_name': '黄金女郎第一季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/6bd086abb26c2293.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '黄金女郎第一季' for key 'PRIMARY'")
2019-04-04 15:05:02 [scrapy.core.scraper] ERROR: Error processing {'detail': '["朱雨辰 罗嘉良 徐光宇", "周小刚", "大陆", "大陆剧 战争片", "普通话对", "2015"]',
 'film_name': '追击者电视剧',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/160712/ece5e2089ef21a0e.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '追击者电视剧' for key 'PRIMARY'")
2019-04-04 15:05:03 [scrapy.core.scraper] ERROR: Error processing {'detail': '["陈晓 严屹宽 郑爽 张芷溪 焦恩俊 谢宁 曹骏 王茂蕾 梁冠华 马书良 刘德凯 李鑫雨 李添诺", "吴家骀", "香港", '
           '"大陆剧 动作片", "国语", "2016"]',
 'film_name': '五鼠闹东京',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/160328/8daf4f0563cd3074.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '五鼠闹东京' for key 'PRIMARY'")
2019-04-04 15:05:17 [scrapy.core.scraper] ERROR: Error processing {'detail': '["马克·哈蒙 尚恩·穆雷 珍妮弗·艾斯波西多", "内详", "美国", "欧美剧", "英语对白", "2016"]',
 'film_name': '海军罪案调查处第十四季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/da18add6aab89e4f.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '海军罪案调查处第十四季' for key 'PRIMARY'")
2019-04-04 15:05:49 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index66321.html> (referer: https://www.1716dy.com/frim/index42-55.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:05:50 [scrapy.core.scraper] ERROR: Error processing {'detail': '["马米·科西科Vincent D\'ArbouzeRatnesh DubeySaskia Slaaf", "内详", "美国", '
           '"欧美剧", "英语", "2017"]',
 'film_name': '搜寻死党第二季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181114/a303cc2e39bfc25a.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'ArbouzeRatnesh DubeySaskia Slaaf", "内详", "美国", "欧美剧", "英语", "2\' at line 1')
2019-04-04 15:06:00 [scrapy.core.scraper] ERROR: Error processing {'detail': '["林周焕 林珠恩 大成 李秀赫 张熙珍", "未知", "韩国", "日韩剧", "内详", "2011"]',
 'film_name': "What's up 电视剧",
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/201888/14751.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'s up 电视剧\',\'电视剧\',\'["林周焕 林珠恩 大成 李秀赫 张熙珍", \' at line 1')
2019-04-04 15:06:05 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index64692.html> (referer: https://www.1716dy.com/frim/index42-58.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:06:05 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index64727.html> (referer: https://www.1716dy.com/frim/index42-58.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:06:10 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index64476.html> (referer: https://www.1716dy.com/frim/index42-59.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:06:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55511.html> (referer: https://www.1716dy.com/frim/index42-60.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:14 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index63116.html> (referer: https://www.1716dy.com/frim/index42-61.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:06:18 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55895.html> (referer: https://www.1716dy.com/frim/index42-62.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:34 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55732.html> (referer: https://www.1716dy.com/frim/index42-67.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:47 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55897.html> (referer: https://www.1716dy.com/frim/index42-68.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:53 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55471.html> (referer: https://www.1716dy.com/frim/index42-70.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:54 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56451.html> (referer: https://www.1716dy.com/frim/index42-70.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:55 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56143.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:06:56 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53580.html> (referer: https://www.1716dy.com/frim/index42-72.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:57 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53517.html> (referer: https://www.1716dy.com/frim/index42-72.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:06:59 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index54638.html> (referer: https://www.1716dy.com/frim/index42-73.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:03 [scrapy.core.scraper] ERROR: Error processing {'detail': '["内详", "保罗·麦奎根", "欧美", "欧美剧", "英语", "2017"]',
 'film_name': '指定幸存者第二季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181130/1c89988846f7a748.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '指定幸存者第二季' for key 'PRIMARY'")
2019-04-04 15:07:06 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55557.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:08 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index54996.html> (referer: https://www.1716dy.com/frim/index42-75.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:16 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index54902.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:16 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index54903.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index56056.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index55896.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:25 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53529.html> (referer: https://www.1716dy.com/frim/index42-71.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:33 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index53111.html> (referer: https://www.1716dy.com/frim/index42-81.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 34, in get_detail
    detail_list.append(response.xpath('//dd[@class="clearfix"]/ul/li[3]/text()').extract()[0])
IndexError: list index out of range
2019-04-04 15:07:37 [scrapy.core.scraper] ERROR: Error processing {'detail': '["威尔·福特 克利欧佩特拉·科尔曼 詹纽瑞·琼斯", "约翰·所罗门", "美国", "欧美剧 动作片", "英语对白", '
           '"2016"]',
 'film_name': ' 一个人的地球第三季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/c2e94c7734ebbda1.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry ' 一个人的地球第三季' for key 'PRIMARY'")
2019-04-04 15:07:40 [scrapy.core.scraper] ERROR: Error processing {'detail': '["让-卢克·比洛多 塔吉·莫里", "迈克尔·莱拜克", "美国", "欧美剧", "英语对白", "2016"]',
 'film_name': '少男奶爸第五季',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/181203/b18440cfc1e3e908.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '少男奶爸第五季' for key 'PRIMARY'")
2019-04-04 15:07:52 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.1716dy.com/movie/index47997.html> (referer: https://www.1716dy.com/frim/index42-88.html)
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/var/www/envpro/lib/python3.5/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/root/lezhangjian/scrapy_doubi/doubiyang/spiders/detail.py", line 40, in get_detail
    img_url = 'https://www.1716dy.comhttps://www.1716dy.com'+re.search(r'url\((.*?)\)',img_url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2019-04-04 15:08:23 [scrapy.core.scraper] ERROR: Error processing {'detail': '["德乌拉·基尔万 安娜·布鲁斯特 迈克尔·兰德斯", "Cilla Ware Philip John Sarah '
           'O\'Gorman", "英国", "欧美剧", "内详", "2010"]',
 'film_name': '物质女孩 电视剧',
 'img_url': 'https://www.1716dy.comhttps://www.1716dy.com/uploads/allimg/201888/14171.jpg',
 'type': '电视剧'}
Traceback (most recent call last):
  File "/var/www/envpro/lib/python3.5/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/root/lezhangjian/scrapy_doubi/doubiyang/pipelines.py", line 57, in process_item
    self.conn.execute("insert into ma_filmdetail values('%s','%s','%s','%s')"%(film_name,type,detail_list,img_url))
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/var/www/envpro/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'Gorman", "英国", "欧美剧", "内详", "2010"]\',\'https://www.1716dy.comhttps:\' at line 1')
